name: Deploy NestJS to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t nestjs-app .

      - name: Save Docker image to tar file
        run: docker save nestjs-app -o nestjs-app.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "nestjs-app.tar"
          target: "/home/ubuntu"

      - name: Run Docker container on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker load -i nestjs-app.tar
            sudo docker stop nestjs-app || true
            sudo docker rm nestjs-app || true
            sudo docker run -d -p 3000:3000 --name nestjs-app nestjs-app
