name: Deploy NestJs to EC2 with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create app archive
        run: tar -czf app.tar.gz .

      - name: Copy app to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.tar.gz"
          target: "/home/ubuntu"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/NestJS-user-document-management || mkdir -p ~/NestJS-user-document-management && cd ~/NestJS-user-document-management
            rm -rf ./*
            tar -xzf ~/app.tar.gz -C ~/NestJS-user-document-management
            cd ~/NestJS-user-document-management

            sudo docker-compose down
            sudo docker-compose up -d --build
